INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1) VALUES
('Concert By The Sea', 'US', 'Concert by the Sea is a live album by pianist Erroll Garner, released on Columbia Records in 1956. It sold over a million dollars worth of retail copies by 1958, thereby qualifying for gold record status by the definition of that time, but has never been acknowledged as such by the RIAA.', 4.07, 'https://img.discogs.com/_j_so4lZL7Gl60Y5mVOU3OsCgZI=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-636663-1345000392-1744.jpeg.jpg', '1956-10-13', 'Jazz');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Hot Rats', 'US', 'Hot Rats is the second solo album by Frank Zappa. This is the first Zappa album on which Dweezil has a credit. Both (he and the album) pretty much came into the world together.',  4.59, 'https://img.discogs.com/OK9dDmCAPSKb5E2mmbHEOhPT5n8=/fit-in/600x598/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-584013-1444143009-3942.jpeg.jpg', '1969-10-10', 'Jazz', 'Rock');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Sgt. Pepper''s Lonely Hearts Club Band', 'UK', 'Sgt. Pepper''s Lonely Hearts Club Band is the eighth studio album by English rock band the Beatles. Released on 26 May 1967 in the United Kingdom and 2 June 1967 in the United States, it was an immediate commercial and critical success, spending 27 weeks at the top of the UK albums chart and 15 weeks at number one in the US.', 4.65, 'https://img.discogs.com/5niM71_Gc3Zkk6VK4cRlpHpQRIY=/fit-in/600x590/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-499497-1456047383-9489.jpeg.jpg', '1967-05-26', 'Rock', 'Psychedelic');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('The Piper At The Gates Of Dawn', 'UK', 'The Piper at the Gates of Dawn is the debut studio album by the English rock band Pink Floyd, and the only one made under founding member Syd Barrett''s leadership.', 4.48, 'https://img.discogs.com/GsJZAmJObvYmkqKuSjpFZcbuJHk=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2901203-1430517077-9122.jpeg.jpg', '1967-08-05', 'Rock', 'Psychedelic');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Lulu', 'US', 'Lulu is a collaborative album between rock singer-songwriter Lou Reed and heavy metal band Metallica. It was released on October 31, 2011 by Warner Bros. in the U.S. and Vertigo elsewhere.', 3.42, 'https://img.discogs.com/mBDUnwvyoTKo5QyTIx08OeU7ffE=/fit-in/470x467/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3200497-1433009730-1356.jpeg.jpg', '2011-10-31', 'Rock', 'Avantgarde');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Minute By Minute', 'US', 'Minute by Minute is the eighth studio album by American rock band The Doobie Brothers, released in 1978. The album contains their biggest hit, the Grammy-winning "What a Fool Believes," which was co-written by Kenny Loggins and simultaneously released on his 1978 album Nightwatch.', 3.64, 'https://img.discogs.com/TZ71KMxLLVM5flj0Tq6LYYiykN4=/fit-in/600x596/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-395838-1331854480.jpeg.jpg', '1978-12-1', 'Pop', 'Rock');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('A Saucerful Of Secrets', 'UK', 'A Saucerful of Secrets is the second studio album by the English rock band Pink Floyd, released on 29 June 1968 by EMI Columbia in the United Kingdom and released on 27 July 1968 in the United States by Tower Records.', 4.31, 'https://img.discogs.com/-py05SBErqzDoi77TYbElzp1GAc=/fit-in/600x597/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2803089-1301740058.jpeg.jpg', '1968-06-29', 'Rock', 'Psychedelic');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Ummagumma', 'UK', 'Ummagumma is the fourth album by the English rock band Pink Floyd. It is a double album and was released on 7 November 1969 by Harvest Records in the United Kingdom and by Capitol Records internationally.', 4.11, 'https://img.discogs.com/z_UiAo4RrL0SQMBNr_4RKSy9Ogo=/fit-in/587x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1645802-1303411599.jpeg.jpg', '1969-10-25', 'Rock', 'Psychedelic');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('More', 'UK', 'More is the first full-length soundtrack album, and third studio album, by the English rock band Pink Floyd, released on 13 June 1969 in the United Kingdom by EMI Columbia and on 9 August 1969 by Tower Records a subsidiary label of Capitol Records in the United States as Original Motion Picture Soundtrack from the film More.', 4.06, 'https://img.discogs.com/YF7rneGUVTGM8kVo_xBhpa_2qS0=/fit-in/600x590/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1240780-1475092749-5675.jpeg.jpg', '1969-06-13', 'Rock', 'Psychedelic');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Atom Heart Mother', 'UK', 'Atom Heart Mother is the fifth studio album by the English progressive rock band Pink Floyd. It was released by Harvest on 2 October 1970 in the UK, and by Capitol on 10 October 1970 in the US.', 4.25, 'https://img.discogs.com/lVSWqAipy64ZCi3zyS2b8tlMo2w=/fit-in/600x588/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2644617-1294700326.jpeg.jpg', '1970-10-02', 'Rock', 'Psychedelic');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Meddle', 'UK', 'Meddle is the sixth studio album by English progressive rock group Pink Floyd, released on 31 October 1971 by Harvest Records.', 4.5, 'https://img.discogs.com/p68Oz1NzpkEJGvGkAphL-q2xYaw=/fit-in/599x596/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-4137493-1356556622-7548.jpeg.jpg', '1971-10-31', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Obscured By Clouds', 'UK', 'Obscured by Clouds is the seventh studio album by the English progressive rock band Pink Floyd, based on their soundtrack for the French film La Vallée, by Barbet Schroeder.', 4.14, 'https://img.discogs.com/Hq2Mf3qSQLd7Jqo43G4b3V_sQwY=/fit-in/600x603/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3092412-1315351289.jpeg.jpg', '1972-06-02', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('The Dark Side of the Moon', 'UK', 'The Dark Side of the Moon is the eighth album by English rock band Pink Floyd, released on 1 March 1973 by Harvest Records.', 4.69, 'https://img.discogs.com/jKTmuxcsYe2TqcahU3QqVXJLssU=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1873013-1471100381-3022.jpeg.jpg', '1973-03-01', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Wish You Were Here', 'UK', 'Wish You Were Here is the ninth studio album by English rock band Pink Floyd. It was released on 12 September 1975 by Harvest Records in the United Kingdom and a day later by Columbia Records in the United States. The album topped record charts in both regions.', 4.71, 'https://img.discogs.com/T4T7uNgiBmcrWP1pfv7BLjdB7u4=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-463597-1477238020-6933.jpeg.jpg', '1975-09-12', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Animals', 'UK', 'Animals is the tenth studio album by English rock band Pink Floyd. It was first released on 23 January 1977 by Harvest Records in the United Kingdom and by Columbia Records in the United States.', 4.53, 'https://img.discogs.com/vBQw6Y9FESBtF8PRIQuw7rPVwxU=/fit-in/600x599/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-391322-1347726103-1009.jpeg.jpg', '1977-01-23', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('The Wall', 'UK', 'The Wall is the eleventh album by English rock band Pink Floyd. It was first released as a double album on 30 November 1979 by Harvest Records in the United Kingdom and by Columbia Records in the United States.', 4.58, 'https://img.discogs.com/p7KdhxY0C7HGtAnIl53OTN0BvV4=/fit-in/588x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2041618-1390679025-2372.jpeg.jpg', '1979-11-30', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('The Final Cut', 'UK', 'The Final Cut is the twelfth studio album by the English progressive rock band Pink Floyd, released on 21 March 1983 by Harvest Records in the United Kingdom and on 2 April by Columbia Records in the United States.', 4.04, 'https://img.discogs.com/TsykxRFCikEaoQoyMl146goWmVs=/fit-in/600x636/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1206134-1318090776.jpeg.jpg', '1983-03-21', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('A Momentary Lapse of Reason', 'UK', 'A Momentary Lapse of Reason is the thirteenth studio album by English progressive rock band Pink Floyd, released in the UK and US on 7 September 1987, on the labels EMI and Columbia.', 4.08, 'https://img.discogs.com/KiMEZISsXb2mzKySkXZR3NCkcrg=/fit-in/600x595/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1201772-1445225696-2685.jpeg.jpg', '1987-09-07', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('The Division Bell', 'UK', 'The Division Bell is the fourteenth studio album by the English progressive rock band Pink Floyd, released on 28 March 1994 by EMI Records in the United Kingdom and on 4 April by Columbia Records in the United States.', 4.4, 'https://img.discogs.com/wekpZfFF3c1tZw9thcrCQfGI_2w=/fit-in/600x596/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1290103-1454722802-4677.jpeg.jpg', '1994-03-28', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('The Endless River', 'UK', 'The Endless River is the fifteenth and final studio album by the English rock band Pink Floyd. It was released on 7 November 2014 in Friday-release countries and on 10 November elsewhere by Parlophone Records in the United Kingdom and by Columbia Records in the United States.', 4.0, 'https://img.discogs.com/4ygmwLbcph6oMUugL5pxq0VDRhA=/fit-in/600x630/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-6278781-1415454372-5440.jpeg.jpg', '2014-11-07', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('American Idiot', 'UK', 'American Idiot is the seventh studio album by American rock band Green Day. Produced by Rob Cavallo, the album was released in the UK on September 20, 2004 and in the US on September 21, 2004 by Reprise Records', 3.5, 'https://images-na.ssl-images-amazon.com/images/I/51H6nwsp6QL.jpg', '2004-09-20', 'Pop', 'Punk');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Physical Graffiti', 'US', 'Physical Graffiti is the sixth studio album by the English rock band Led Zeppelin, released as a double album on 24 February 1975 by their newly founded imprint label Swan Song Records.', 4.8, 'https://upload.wikimedia.org/wikipedia/en/e/e3/Led_Zeppelin_-_Physical_Graffiti.jpg', '1975-02-24', 'Rock', 'Progressive');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Back in Black', 'Australia', 'Back in Black is the seventh studio album by Australian rock band AC/DC. Produced by Robert John "Mutt" Lange, the album was released on 25 July 1980 by Albert Productions and Atlantic Records.', 4.1, 'https://upload.wikimedia.org/wikipedia/pt/b/b6/Back_in_Black.jpg', '1980-07-25', 'Rock', 'Hard');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Still Not Getting Any...', 'Canada', 'Still Not Getting Any... is the second studio album by Canadian rock band Simple Plan. It was released on October 26, 2004 by Lava Records.', 3.7, 'https://upload.wikimedia.org/wikipedia/pt/1/12/StillNotGettingAny.jpg', '2004-10-26', 'Pop', 'Rock');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
('Ghost Stories', 'US', 'Ghost Stories is the sixth studio album by British rock band Coldplay. Co-produced by the band with Paul Epworth along with returning Mylo Xyloto producers Daniel Green and Rik Simpson, it was released by Parlophone on 16 May 2014.', 4.2, 'https://upload.wikimedia.org/wikipedia/en/8/8a/Coldplay_-_Ghost_Stories.png', '2014-05-16', 'Pop', 'Electronic');



