INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1) VALUES
			('Concert By The Sea', 'US', 'Concert by the Sea is a live album by pianist Erroll Garner, released on Columbia Records in 1956. It sold over a million dollars worth of retail copies by 1958, thereby qualifying for gold record status by the definition of that time, but has never been acknowledged as such by the RIAA.', 4.07, 'https://img.discogs.com/_j_so4lZL7Gl60Y5mVOU3OsCgZI=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-636663-1345000392-1744.jpeg.jpg', '1956-10-13', 'Jazz');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
			('Hot Rats', 'US', 'Hot Rats is the second solo album by Frank Zappa. This is the first Zappa album on which Dweezil has a credit. Both (he and the album) pretty much came into the world together.',  4.59, 'https://img.discogs.com/OK9dDmCAPSKb5E2mmbHEOhPT5n8=/fit-in/600x598/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-584013-1444143009-3942.jpeg.jpg', '1969-10-10', 'Jazz', 'Rock');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
			('Sgt. Pepper''s Lonely Hearts Club Band', 'UK', 'Sgt. Pepper''s Lonely Hearts Club Band is the eighth studio album by English rock band the Beatles. Released on 26 May 1967 in the United Kingdom and 2 June 1967 in the United States, it was an immediate commercial and critical success, spending 27 weeks at the top of the UK albums chart and 15 weeks at number one in the US.', 4.65, 'https://img.discogs.com/5niM71_Gc3Zkk6VK4cRlpHpQRIY=/fit-in/600x590/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-499497-1456047383-9489.jpeg.jpg', '1967-05-26', 'Rock', 'Psychedelic');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
			('The Piper At The Gates Of Dawn', 'UK', 'The Piper at the Gates of Dawn is the debut studio album by the English rock band Pink Floyd, and the only one made under founding member Syd Barrett''s leadership.', 4.48, 'https://img.discogs.com/GsJZAmJObvYmkqKuSjpFZcbuJHk=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2901203-1430517077-9122.jpeg.jpg', '1967-08-05', 'Rock', 'Psychedelic');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
			('Lulu', 'US', 'Lulu is a collaborative album between rock singer-songwriter Lou Reed and heavy metal band Metallica. It was released on October 31, 2011 by Warner Bros. in the U.S. and Vertigo elsewhere.', 3.42, 'https://img.discogs.com/mBDUnwvyoTKo5QyTIx08OeU7ffE=/fit-in/470x467/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3200497-1433009730-1356.jpeg.jpg', '2011-10-31', 'Rock', 'Avantgarde');
INSERT INTO album(nome, pais, descricao, avaliacao, capa, data_publicacao, genero1, genero2) VALUES
			('Minute By Minute', 'US', 'Minute by Minute is the eighth studio album by American rock band The Doobie Brothers, released in 1978. The album contains their biggest hit, the Grammy-winning "What a Fool Believes," which was co-written by Kenny Loggins and simultaneously released on his 1978 album Nightwatch.', 3.64, 'https://img.discogs.com/TZ71KMxLLVM5flj0Tq6LYYiykN4=/fit-in/600x596/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-395838-1331854480.jpeg.jpg', '1978-12-1', 'Pop', 'Rock');