INSERT INTO gravacao VALUES
(1,1);
INSERT INTO gravacao VALUES
(2,5);
INSERT INTO gravacao VALUES
(3,4);
INSERT INTO gravacao VALUES
(4,2);
INSERT INTO gravacao VALUES
(5,6);
INSERT INTO gravacao VALUES
(5,7);
INSERT INTO gravacao VALUES
(6,3);
INSERT INTO gravacao VALUES
(7, 2);
INSERT INTO gravacao VALUES
(8, 2);
INSERT INTO gravacao VALUES
(9, 2);
INSERT INTO gravacao VALUES
(10, 2);
INSERT INTO gravacao VALUES
(11, 2);
INSERT INTO gravacao VALUES
(12, 2);
INSERT INTO gravacao VALUES
(13, 2);
INSERT INTO gravacao VALUES
(14, 2);
INSERT INTO gravacao VALUES
(15, 2);
INSERT INTO gravacao VALUES
(16, 2);
INSERT INTO gravacao VALUES
(17, 2);
INSERT INTO gravacao VALUES
(18, 2);
INSERT INTO gravacao VALUES
(19, 2);
INSERT INTO gravacao VALUES
(20, 2);
INSERT INTO gravacao VALUES
(21, 8);
INSERT INTO gravacao VALUES
(22, 9);
INSERT INTO gravacao VALUES
(23, 10);
INSERT INTO gravacao VALUES
(24, 11);
INSERT INTO gravacao VALUES
(25, 12);
INSERT INTO gravacao VALUES
(52, 6);
INSERT INTO gravacao VALUES
(53, 6);
INSERT INTO gravacao VALUES
(54, 6);
INSERT INTO gravacao VALUES
(55, 6);
INSERT INTO gravacao VALUES
(56, 6);
INSERT INTO gravacao VALUES
(57, 6);
INSERT INTO gravacao VALUES
(58, 6);
INSERT INTO gravacao VALUES
(59, 6);
INSERT INTO gravacao VALUES
(60, 6);
INSERT INTO gravacao VALUES
(61, 6);
INSERT INTO gravacao VALUES
(62, 6);
INSERT INTO gravacao VALUES
(63, 6);
INSERT INTO gravacao VALUES
(64, 6);
INSERT INTO gravacao VALUES
(65, 6);
INSERT INTO gravacao VALUES
(66, 6);